import { StyleSheet, Dimensions } from "react-native";
const { width: WIDTH, height: HEIGHT } = Dimensions.get("screen");
export default StyleSheet.create({
  container: {
    flex: 1,
    
  },
//   leftContainer:{
//     flex:0,
//     backgroundColor: '#ca8afa',    
// },
// rightContainer:{
//     flex:1,
//     backgroundColor: '#96d0e3'

// },
  header: {
    flex: 1 / 1.5,
    backgroundColor: "#a8dfd2",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    justifyContent: "center",
    alignContent: "center"
  },
  footer: {
    flex: 1,
    backgroundColor: "#fff",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingVertical: 30,
    paddingHorizontal: 30,
  },
  image: {
    flex: 1,
    margin: 100,
    alignItems: "center",
    justifyContent: "center",
  },

 
  dotView: {
    marginBottom: 20,
    flexDirection: "row",
    justifyContent: "center",
  },
  dot: {
    height: 10,
    width: 10,
    backgroundColor: "#fff",
    margin: 8,
    borderRadius: 5,
  },

  title: {
    color: "#04011f",
    fontSize: 28,
    fontWeight: "bold",
  },
  PriceContainer: {
    flexDirection: "row",
  },
  price: {
    color: "#3ea806",
    fontSize: 20,
    textAlign: "center",
    fontWeight: "bold",
    margin: 8,
  },
  
  btncontainer: {
    marginLeft: 100,
    backgroundColor: "#0095ff",
    width: 130,
    height: 40,
    padding: 8,
    borderRadius: 10,
  },
  btntext: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  // infoBoxWrapper: {
  //   borderBottomColor: "transparent",
  //   borderBottomWidth: 12,
  //   borderTopColor: "transparent",
  //   borderTopWidth: 1,
  //   flexDirection: "row",
  //   height: 100,
  // },
  // infoBox: {
  //   margin: -10,
  //   width: "35%",
  //   marginRight: 5,
  //   alignItems: "center",
  //   justifyContent: "center",
  //   borderRightColor: "transparent",
  //   flexDirection: "row",
  //   borderRightWidth: 1,
  // },
  caption: {
    fontSize: 20,
    color: "black",
    fontWeight: "normal",
    marginLeft: 10,
  },
  description: {
    color: "#060607",
    fontSize: 20,
  },
  //   viewmore: {
  //     flexDirection: "row",
  //   },
  cart: {
    margin: 10,
    marginTop: 10,
    marginLeft: 10,
    flexDirection: "row",
    marginBottom: 10,
  },
  cartbtn: {
    backgroundColor: "#64b903",
    width: 140,
    marginLeft: 30,
    borderRadius: 10,
  },
  cartbtntext: {
    color: "blue",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    padding: 10,
  },
  buynow: {
    margin: 10,
    marginTop: 16,
    marginRight: 10,
    flexDirection: "row",
    marginBottom: 10,
  },
  buynowbtn: {
    backgroundColor: "#64b903",
    width: WIDTH - 140,
    marginLeft: 30,
    borderRadius: 10,
  },
  buynowbtntext: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    padding: 10,
  },
  subtitle: {
    color: "#04011f",
    fontSize: 24,
    fontWeight: "bold",
  },
  Checkout: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderWidth: 0.5,
    borderColor: "grey",
    backgroundColor: "#fff",
    height: 60,
    width: "100%",
    // shadowColor: "red",
    // shadowOffset: { width: 1, height: 1 },
    // shadowOpacity: 0.5,
    // shadowRadius: 3,
    // elevation: 5,
  },
  Checkoutbtn: {
    backgroundColor: "#64b903",
    height: 60,
    width: "100%",
    borderRadius: 15,
    marginTop: 130,
    shadowColor: "#000",
    shadowOpacity: 0.5,
    shadowRadius: 3,
    flexDirection: "row",
  },
  checkoutbtntext1: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "left",
    padding: 15,
  },
  checkoutbtntext2: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "right",
    padding: 15,
    marginLeft: 150,
  },
  checkouticon: {
    color: "white",
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "right",
    paddingTop: 15,
  },
  cardView: {
    flex: 1,
    width:20,
    height: 30,
    backgroundColor: "white",
    margin: 5,
    borderRadius: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0.5, height: 0.5 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
    elevation: 2,
  },
});